{"uuid": "d2870b4b-2fb0-493e-a9a4-2e606bfca6c7", "children": ["bef274c4-5632-4972-9ed4-430f28326f1e"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 0\n\n", "trace": "  File \"C:\\Users\\User\\Desktop\\python\\python\\python\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\User\\Desktop\\python\\python\\python\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\User\\Desktop\\python\\python\\python\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\User\\Desktop\\python\\python\\python\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\User\\Desktop\\python\\python\\python\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\User\\Desktop\\python\\python\\python\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\User\\Desktop\\python\\python\\python\\10_lesson\\test_02_swag_page_obj.py\", line 19, in driver\n    driver = webdriver.Firefox(service=Service(GeckoDriverManager().install()))\n  File \"C:\\Users\\User\\Desktop\\python\\python\\python\\venv\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 72, in __init__\n    super().__init__(command_executor=executor, options=options)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\Desktop\\python\\python\\python\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 257, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\Desktop\\python\\python\\python\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 356, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\Desktop\\python\\python\\python\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\User\\Desktop\\python\\python\\python\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1753287800206, "stop": 1753287812988}], "start": 1753287800206, "stop": 1753287813035}